# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblee', '0005_auto_20180629_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='recipe',
        ),
        migrations.AddField(
            model_name='day',
            name='recipe',
            field=models.ManyToManyField(blank=True, null=True, to='grumblee.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='foodItems',
            field=models.ManyToManyField(blank=True, null=True, to='grumblee.FoodItem'),
        ),
    ]
