# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblee', '0006_auto_20180703_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='recipe',
            new_name='recipes',
        ),
    ]
