# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblee', '0008_auto_20180706_0032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodItem',
            new_name='Ingredient',
        ),
        migrations.RenameField(
            model_name='groceryitem',
            old_name='foodItem',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='foodItems',
            new_name='ingredients',
        ),
    ]
