# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblee', '0010_auto_20180706_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='overrideVal',
            field=models.IntegerField(default=0),
        ),
    ]
