# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grumblee', '0004_auto_20180629_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='name',
        ),
        migrations.AlterField(
            model_name='day',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grumblee.Recipe'),
        ),
    ]
