# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grumblee', '0012_auto_20180710_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grumblee.Week'),
        ),
    ]
